# Generated by Django 4.2.5 on 2023-09-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="save_configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Frequency", models.CharField(max_length=10)),
                ("Noise_level", models.CharField(max_length=10)),
                ("Trend_coefficient", models.CharField(default="0", max_length=10)),
                ("Missing_percentage", models.IntegerField(default=0)),
                ("Outlier_percentage", models.IntegerField(default=0)),
                ("Cycle_component_amplitude", models.BooleanField()),
                ("Cycle_component_frequency", models.IntegerField()),
                ("Status", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="simulator_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("use_case_name", models.CharField(max_length=30)),
                ("time_series_type", models.CharField(max_length=14)),
                ("meta_data", models.CharField(max_length=30)),
                ("producer_type", models.CharField(max_length=30)),
            ],
        ),
    ]
