# Generated by Django 4.2.5 on 2023-09-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeseries", "0003_save_configuration_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="save_configuration",
            name="Cycle_component_amplitude",
        ),
        migrations.RemoveField(
            model_name="save_configuration",
            name="Cycle_component_frequency",
        ),
        migrations.RemoveField(
            model_name="simulator_details",
            name="meta_data",
        ),
        migrations.AlterField(
            model_name="seasonality_component",
            name="amplitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="seasonality_component",
            name="phase_shift",
            field=models.FloatField(),
        ),
    ]
